// Generated by scripts/vendor-lsp-backend.ts; verify versions before updating.
export const AUTO_BACKEND = Object.freeze({
  server: "6.0.1",
  typescript: "6.0.3",
  sha256: "2784092fa25db2cba08ac8341db91c557763def732e8e94de63fc26b262f50e4",
});
