import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { gzipSync } from "node:zlib";

// Explicit maintainer operation, never run by the CLI, npm install, or a project.
// Input: an installation of typescript-language-server@6.0.1 and typescript@6.0.3.
const installation = resolve(process.argv[2] ?? "");
if (!process.argv[2])
  throw new Error("Pass the pinned installation's node_modules directory.");
const files: Record<string, string> = {};
for (const [name, version] of [
  ["typescript-language-server", "6.0.1"],
  ["typescript", "6.0.3"],
] as const) {
  const root = join(installation, name);
  const metadata = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
  if (metadata.name !== name || metadata.version !== version)
    throw new Error("Unexpected backend version.");
  const names = name === "typescript"
    ? ["package.json", "LICENSE.txt", "ThirdPartyNoticeText.txt",
      ...(await readdir(join(root, "lib")))
        .filter(name => /\.(?:js|json|d\.ts)$/.test(name))
        .sort().map(name => `lib/${name}`)]
    : ["package.json", "LICENSE", "lib/cli.mjs"];
  for (const file of names)
    files[`${name}/${file}`] = await readFile(join(root, file), "utf8");
}
const bytes = gzipSync(Buffer.from(JSON.stringify(files)), { level: 9 });
const digest = createHash("sha256").update(bytes).digest("hex");
const destination = resolve(import.meta.dir, "../src/lsp/backend");
await mkdir(destination, { recursive: true });
await writeFile(join(destination, "typescript.json.gz"), bytes);
await writeFile(join(destination, "version.ts"), `// Generated by scripts/vendor-lsp-backend.ts; verify versions before updating.\nexport const AUTO_BACKEND = Object.freeze({\n  server: "6.0.1",\n  typescript: "6.0.3",\n  sha256: "${digest}",\n});\n`);
console.log(`Vendored ${Object.keys(files).length} files, ${bytes.length} bytes; SHA-256 ${digest}`);
